Repository Shirisu/autoPetiteTCGScript, pull requests merged in 2021-03, with the labels that each got.

#16 bugfix - enable subfolder usage
  DOCUMENTATION.md
  README.md
  assets/js/script.js
  inc/class.Route.php
  inc/constants.php
  inc/footer.php
Labels: bug, documentation

#27 bugfix - allow subcategories with same name in different main categories
  README.md
  admin/subcategory_add.php
  admin/subcategory_edit.php
  inc/translations/de.php
  inc/translations/en.php
Labels: bug

#38 bugfix - registration sends no mails with umlauts in subject
  inc/header.php
  tcg/lostpassword.php
  tcg/register.php
Labels: bug

#53 bugfix - wrong translation for level up reward
  inc/translations/en.php
Labels: bug

#54 bugfix - memory infinite loop
  tcg/games/memory.php
Labels: bug

#55 bugfix - delete char limitation for imagesources
  admin/carddeck_add.php
  admin/carddeck_edit.php
Labels: bug

#56 feature - add memberlink to trade log texts
  tcg/trade/trade.php
Labels: bug, enhancement

#57 feature - deck mastering
  assets/css/style.css
  inc/function.php
  inc/translations/de.php
  inc/translations/en.php
  tcg/cards/cards_collect.php
Labels: enhancement

#61 feature - send message for accept or decline trade
  tcg/trade/trade.php
Labels: enhancement

#60 feature - show member nick on trade offer page
  tcg/trade/trade_offer.php
Labels: enhancement

#62 bugfix - member nick on trade offer page
  assets/css/style.css
  tcg/trade/trade_offer.php
Labels: bug
